# Enable NSIB (b0) as the first-stage immutable bootloader
SB_CONFIG_SECURE_BOOT_APPCORE=y

# Enable MCUboot as the second-stage upgradable bootloader
SB_CONFIG_BOOTLOADER_MCUBOOT=y

# image0 = bank0, image1 = bank1
SB_CONFIG_MCUBOOT_UPDATEABLE_IMAGES=2

# Use partition manager with the static YAML in the project root
SB_CONFIG_PARTITION_MANAGER=y

# Operational mode: swap (default)
SB_CONFIG_MCUBOOT_MODE_SWAP_USING_MOVE=y
#SB_CONFIG_MCUBOOT_MODE_OVERWRITE_ONLY=n

# Use external flash
SB_CONFIG_PM_EXTERNAL_FLASH_MCUBOOT_SECONDARY=y
SB_CONFIG_PM_OVERRIDE_EXTERNAL_DRIVER_CHECK=y
