manifest:
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: savosaicic
      url-base: https://github.com/savosaicic

  projects:
    - name: nrf
      repo-path: sdk-nrf
      remote: savosaicic
      revision: lwm2m-fota-multi-image-support
      import: true

  self:
    path: nrf-multi-image-fota
